database:
  driver: "pg"
  host: "localhost"
  port: 5432
  username: "webhook"
  name: "webhook_relay"
  password: "webhook"
  dsn: "postgres://webhook:webhook@5432/webhook_relay?sslmode=false"

app:
  host: "localhost"
  port: 3000

kafka:
  topic: "events"
  brokers:
    - "localhost:9092"