database:
  driver: "pg"
  host: "localhost"
  port: 5432
  username: "webhook"
  name: "webhook_relay"
  password: "webhook"
  dsn: "postgresql://webhook:webhook@localhost:5432/webhook_relay"


app:
  host: "localhost"
  port: 3000

kafka:
  topic: "events"
  brokers:
    - "localhost:9092"

logger:
  dev: true